app = 'proto-fly-test'
primary_region = 'lhr'

[build]

[env]
PORT = "8080"

[deploy]
strategy = "immediate"

[[vm]]
size = 'shared-cpu-1x'

[[services]]
internal_port = 8080
protocol = "tcp"
http_checks = [
  { interval = "15s", timeout = "2s", grace_period = "1s", method = "GET", path = "/healthcheck" },
]

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["tls", "http"]
port = 443
tls_options = { "alpn" = ["h2"] }

[services.ports.http_options]
h2_backend = true

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "1s"
